

##Basic Packages Import statement

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

##Data Collection and Preprocessing

In [3]:
data = pd.read_csv('D:\Project\Dataset\Training.csv')

In [4]:
data

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
0                     0                         Fungal infection  
1                     0                         Fungal infection  
2                     0                         Fungal infection  
3                     0                         Fungal infection  
4                     0                    

In [5]:
data.shape

(4920, 133)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [7]:
data.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

##Dependent and Independent data split

In [8]:
X = data.drop('prognosis', axis=1)
y = data['prognosis']

##LabelEncoder for Target variables

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()
le.fit(y)
Y = le.transform(y)

In [11]:
Y_label_dict = dict(zip(le.transform(le.classes_), le.classes_))
Y_label_dict

{0: '(vertigo) Paroymsal  Positional Vertigo',
 1: 'AIDS',
 2: 'Acne',
 3: 'Alcoholic hepatitis',
 4: 'Allergy',
 5: 'Arthritis',
 6: 'Bronchial Asthma',
 7: 'Cervical spondylosis',
 8: 'Chicken pox',
 9: 'Chronic cholestasis',
 10: 'Common Cold',
 11: 'Dengue',
 12: 'Diabetes ',
 13: 'Dimorphic hemmorhoids(piles)',
 14: 'Drug Reaction',
 15: 'Fungal infection',
 16: 'GERD',
 17: 'Gastroenteritis',
 18: 'Heart attack',
 19: 'Hepatitis B',
 20: 'Hepatitis C',
 21: 'Hepatitis D',
 22: 'Hepatitis E',
 23: 'Hypertension ',
 24: 'Hyperthyroidism',
 25: 'Hypoglycemia',
 26: 'Hypothyroidism',
 27: 'Impetigo',
 28: 'Jaundice',
 29: 'Malaria',
 30: 'Migraine',
 31: 'Osteoarthristis',
 32: 'Paralysis (brain hemorrhage)',
 33: 'Peptic ulcer diseae',
 34: 'Pneumonia',
 35: 'Psoriasis',
 36: 'Tuberculosis',
 37: 'Typhoid',
 38: 'Urinary tract infection',
 39: 'Varicose veins',
 40: 'hepatitis A'}

##Data spliting into training and testing in 7:3 ratio

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42, stratify=Y)

In [14]:
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(3444, 132) (3444,) (1476, 132) (1476,)


##Model Building

In [15]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [16]:
models = {
    'SVC':SVC(kernel='linear'),
    'KNN':KNeighborsClassifier(),
    'RF':RandomForestClassifier(),
    'NB':GaussianNB()
}

##Model Evaluation

In [17]:
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(f'Accuracy Score of the {name} model is, ', accuracy_score(y_test, y_pred))
    print(f'Confusion Matrix of the {name} model is, \n', confusion_matrix(y_test, y_pred))
    print('*'*100)

Accuracy Score of the SVC model is,  1.0
Confusion Matrix of the SVC model is, 
 [[36  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 36 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 36]]
****************************************************************************************************
Accuracy Score of the KNN model is,  1.0
Confusion Matrix of the KNN model is, 
 [[36  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 36 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 36]]
****************************************************************************************************
Accuracy Score of the RF model is,  1.0
Confusion Matrix of the RF model is, 
 [[36  0  0 ...  0  0  0]
 [ 0 36  0 ...  0  0  0]
 [ 0  0 36 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 36]]
*****************************************************************************************

##Single Model Evaluation

In [18]:
svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
y_pred = svc.predict(x_test)
print(f'Accuracy Score of the SVC model is, ', accuracy_score(y_test, y_pred))

Accuracy Score of the SVC model is,  1.0


In [19]:
import pickle

with open('Personalized_Healthcare\prediction\model.pkl', 'wb') as pkl:
	pickle.dump(svc, pkl)

In [20]:
x_data = X.iloc[0].values.reshape(1, -1)
x_data

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

##Sample Prediction

In [21]:
y_pred = svc.predict(x_data)
print(f'Actual disease: {data.prognosis[0]}')
print(f'Predicted disease: {Y_label_dict[y_pred[0]]}')

Actual disease: Fungal infection
Predicted disease: Fungal infection


In [22]:
y_pred

array([15])

##Creating Dictionary for symptoms and Diseases

In [23]:
symptoms_columns = np.asarray(data.columns)
symptoms_dict = dict()
for index, column in enumerate(symptoms_columns):
    symptoms_dict[column] = index

In [24]:
symptoms_dict.pop('prognosis')

132

###Symptoms Dictionary

In [25]:
symptoms_dict

{'itching': 0,
 'skin_rash': 1,
 'nodal_skin_eruptions': 2,
 'continuous_sneezing': 3,
 'shivering': 4,
 'chills': 5,
 'joint_pain': 6,
 'stomach_pain': 7,
 'acidity': 8,
 'ulcers_on_tongue': 9,
 'muscle_wasting': 10,
 'vomiting': 11,
 'burning_micturition': 12,
 'spotting_ urination': 13,
 'fatigue': 14,
 'weight_gain': 15,
 'anxiety': 16,
 'cold_hands_and_feets': 17,
 'mood_swings': 18,
 'weight_loss': 19,
 'restlessness': 20,
 'lethargy': 21,
 'patches_in_throat': 22,
 'irregular_sugar_level': 23,
 'cough': 24,
 'high_fever': 25,
 'sunken_eyes': 26,
 'breathlessness': 27,
 'sweating': 28,
 'dehydration': 29,
 'indigestion': 30,
 'headache': 31,
 'yellowish_skin': 32,
 'dark_urine': 33,
 'nausea': 34,
 'loss_of_appetite': 35,
 'pain_behind_the_eyes': 36,
 'back_pain': 37,
 'constipation': 38,
 'abdominal_pain': 39,
 'diarrhoea': 40,
 'mild_fever': 41,
 'yellow_urine': 42,
 'yellowing_of_eyes': 43,
 'acute_liver_failure': 44,
 'fluid_overload': 45,
 'swelling_of_stomach': 46,
 'swelle

###Disease Dictionary

In [26]:
Y_label_dict = dict(zip(le.transform(le.classes_), le.classes_))
Y_label_dict

{0: '(vertigo) Paroymsal  Positional Vertigo',
 1: 'AIDS',
 2: 'Acne',
 3: 'Alcoholic hepatitis',
 4: 'Allergy',
 5: 'Arthritis',
 6: 'Bronchial Asthma',
 7: 'Cervical spondylosis',
 8: 'Chicken pox',
 9: 'Chronic cholestasis',
 10: 'Common Cold',
 11: 'Dengue',
 12: 'Diabetes ',
 13: 'Dimorphic hemmorhoids(piles)',
 14: 'Drug Reaction',
 15: 'Fungal infection',
 16: 'GERD',
 17: 'Gastroenteritis',
 18: 'Heart attack',
 19: 'Hepatitis B',
 20: 'Hepatitis C',
 21: 'Hepatitis D',
 22: 'Hepatitis E',
 23: 'Hypertension ',
 24: 'Hyperthyroidism',
 25: 'Hypoglycemia',
 26: 'Hypothyroidism',
 27: 'Impetigo',
 28: 'Jaundice',
 29: 'Malaria',
 30: 'Migraine',
 31: 'Osteoarthristis',
 32: 'Paralysis (brain hemorrhage)',
 33: 'Peptic ulcer diseae',
 34: 'Pneumonia',
 35: 'Psoriasis',
 36: 'Tuberculosis',
 37: 'Typhoid',
 38: 'Urinary tract infection',
 39: 'Varicose veins',
 40: 'hepatitis A'}

##Disease Name Prediction

In [27]:
def get_perdicted_disease(input_symptoms):
    input_data = np.zeros(len(symptoms_dict))
    for items in input_symptoms:
        input_data[symptoms_dict[items]] = 1
    input_data = input_data.reshape(1, -1)
    y_pred = svc.predict(input_data)
    return Y_label_dict[y_pred[0]]

In [28]:
input_symptoms = ['itching', 'skin_rash', 'nodal_skin_eruptions']
predicted_disease = get_perdicted_disease(input_symptoms)
print(f'Predicted disease: {predicted_disease}')

Predicted disease: Fungal infection


##Reading All Other Attributes for Disease

In [29]:
symptoms_severity = pd.read_csv('D:\Project\Dataset\Symptom-severity.csv')
description = pd.read_csv('D:\Project\Dataset\description.csv')
precaution = pd.read_csv('D:\Project\Dataset\precautions.csv')
diets = pd.read_csv('D:\Project\Dataset\diets.csv')
symptoms = pd.read_csv('D:\Project\Dataset\symptoms.csv')
workouts = pd.read_csv('D:\Project\Dataset\workouts.csv')
medications = pd.read_csv('D:\Project\Dataset\medications.csv')

##Functions for getting Attributes

In [33]:
def get_description(disease):
    return description[description['Disease'] == disease]['Description'][0]

def get_diets(disease):
    return diets[diets['Disease'] == disease]['Diet'][0]

def get_precautions(disease):
    pre = precaution[precaution['Disease'] == disease][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']].values
    return pre[0]

def get_workouts(disease):
    return np.asarray(workouts[workouts['disease'] == disease]['workout'])

def get_medications(disease):
    return medications[medications['Disease'] == disease]['Medication'][0]

def get_symptoms(disease):
    sym = symptoms[symptoms['Disease'] == disease][['Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4']].dropna()
    sym1 = sym.Symptom_1.unique().tolist()
    sym2 = sym.Symptom_2.unique().tolist()
    sym3 = sym.Symptom_3.unique().tolist()
    sym4 = sym.Symptom_4.unique().tolist()
    all_symptoms = sym1 + sym2 + sym3 + sym4
    return all_symptoms

In [35]:
des = get_description(predicted_disease)
print('Description : ', list(des))
print('')
pre = get_precautions(predicted_disease)
print('Precautions : ', pre)
print('')
diet = get_diets(predicted_disease)
print('Diets : ', diet)
print('')
med = get_medications(predicted_disease)
print('Medications : ', med)
print('')
work = get_workouts(predicted_disease)
print('Workouts : ', work)
print('')
sym = get_symptoms(predicted_disease)
print('Common Symptoms : ', sym)

Description :  ['Fungal infection is a common skin condition caused by fungi.']

Precautions :  [['bath twice' 'use detol or neem in bathing water'
  'keep infected area dry' 'use clean cloths']]

Diets :  ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']

Medications :  ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']

Workouts :  ['Avoid sugary foods' 'Consume probiotics' 'Increase intake of garlic'
 'Include yogurt in diet' 'Limit processed foods' 'Stay hydrated'
 'Consume green tea' 'Eat foods rich in zinc' 'Include turmeric in diet'
 'Eat fruits and vegetables']

Common Symptoms :  ['itching', ' skin_rash', ' nodal_skin_eruptions', ' dischromic _patches']
